### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by Lernos** [AttorneyOnlineVidya/tsuserver#33]
So, I'm assuming it is possible to use this server in its current state? I just wanted to do some testing, so I compiled it in go (it complained there were files missing, so I used the "go get" command and it got all the files and created the .exe for me), set up the config.toml and launched the .exe. However, it told me it required banlist.json and polls.json in the storage folder and refused to run ("The system cannot find the file specified"). Is there something I'm doing wrong or..?

P. S. I'm using Windows 8.1 x64

**Comment by Lewdton** [comment]
See this doc https://docs.google.com/document/d/10RH8MRbdiyKEEAzIQPB4dXJcvhROwdWXmPfgsuk3whU/edit

It doesn't matter if the json files are there but you MUST have the config files.

**Comment by Lernos** [comment]
You see, I've already read this guide through a couple of times, thank you very much. I have all the config files, no problem with that. The _problem_ is that when I run the .exe it _won't do anything_ because the banlist and polls files are not there. I've specified the _error_ it gives me: "The system cannot find the file specified." So, it won't work unless these files are there, but it won't create them automatically (like the doc says it _will_) either. What could be wrong here then? Did I compile it right?

**Comment by Lewdton** [comment]
What are you using to compile it? That should not stop the server from running, it only throws out the error to let you know it cant find them.

EDIT: Doc is wrong, it'll only create those file when you first ban someone/create a poll, I'll change that.

**Comment by Lernos** [comment]
I'm using go. To be more specific, it goes like this:
- I unpack the zip to, let's say, C:\, so now we have C:\tsuserver-master
- I launch cmd and "cd" to C:\tsuserver-master
- I set GOPATH and GOBIN to be C:\tsuserver-master
- I input the command "go get"
- All needed files and folders, like "src", are downloaded, the project seems to be compiled, there is now tsuserver-master.exe in C:\tsuserver-master

So yes, I have all config files and everything is set up. In fact, perhaps you're right and the server _is working_ de jure, but! When I try to launch my Attorney Online client, it says "Test server is not a valid integer value." And it's not on the list, obviously.
![2](https://cloud.githubusercontent.com/assets/21978347/18249986/d9cafc9c-7389-11e6-892d-a4f144e7535a.png)
![default](https://cloud.githubusercontent.com/assets/21978347/18249998/f946cf4c-7389-11e6-9c66-5b120b5386d2.png)

**Comment by Lewdton** [comment]
God bless the master server, remove the # from your Servername.

**Comment by Lernos** [comment]
Oh. Facepalming as hard as I can. Well, I reckon the case is closed then, thank you for your time >_<

**Comment by Lewdton** [comment]
No worries, I'll update the doc accordingly.
